[world]
name = "Provable Games"
description = "PG Sepolia World"
seed = "DNC"

[namespace]
default = "ds_v1_2_1"

[writers]
"ds_v1_2_1" = [
    "ds_v1_2_1-game_systems",
    "ds_v1_2_1-battle_systems",
    "ds_v1_2_1-config_systems",
]

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x01bfa92665fb815c9ec5f37c562a5c9a06fdf23ce022c1d33d4ac07cef5ad80c"

[init_call_args]
"ds_v1_2_1-game_systems" = [
    "0x0238df9Efd27Aba2ccB0bdC97a4cf440caA403e9ed3f1883294Ab6CDBA6C5282",
]